### ISSUE TITLE
Can not encode with intel quicksync - Returns [hevc_vaapi @ 0x55d40be03100] No usable encoding profile found.

### ISSUE THREAD

**Issue by anzenketh** [djaydev/docker-recordings-transcoder#3]
Docker Compose script:
```
  recodings-converter:
    image: djaydev/recordings-converter
    container_name: recordings-converter
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /nas/com-skip/output/watch:/watch:rw
      - $DOCKERDIR/recordings-transcoder:/config:rw
    devices:
      - /dev/dri:/dev/dri # for harware transcoding
    environment:
      - ENCODER: intel
      - SUBTITLES: 0
      - DELETE_TS: 0
      PUID: $PUID
      GUID: 44
      TZ: $TZ
```

Logs attached. 
[postProcess.26-07-2020-0144.log](https://github.com/djaydev/docker-recordings-transcoder/files/4977318/postProcess.26-07-2020-0144.log)
